v0.9.8-5: Forcing update installation for now (it looks like some devices -- 3.0.[45] TP -- have discrepancies between installed OpenSSL files and their reference checksum in /md5sums.gz, an OTA issue???)

diff --git a/control/postinst b/control/postinst
--- a/control/postinst
+++ b/control/postinst
@@ -1,6 +1,7 @@
 #!/bin/sh
 
 PID="org.webosinternals.openssl-updater"
+FORCE_INSTALL="1"
 
 # Handle execution as pmPostInstall.script
 if [ -z "$IPKG_OFFLINE_ROOT" ]; then
@@ -23,17 +24,21 @@ error=0
 # Make sure all existing target files are in virgin condition
 echo "Verifying no existing modifications to target files ..."
 for file in `find usr -type f -print` ; do
-  md5sum1="`cat  /md5sums    | grep    -e \*./$file$ | awk '{print $1}'`"
-  md5sum2="`zcat /md5sums.gz | grep -h -e \*./$file$ | awk '{print $1}'`"
-  [ ! -f "/$file" ] || \
-      [ "`md5sum /$file | awk '{print $1}'`" = "$md5sum1" ] || \
-      [ "`md5sum /$file | awk '{print $1}'`" = "$md5sum2" ] || \
-      { echo "Verification failed on /$file" ; error=1 ; }
+    md5sum1="`cat  /md5sums    | grep    -e \*./$file$ | awk '{print $1}'`"
+    md5sum2="`zcat /md5sums.gz | grep -h -e \*./$file$ | awk '{print $1}'`"
+    [ ! -f "/$file" ] || \
+        [ "`md5sum /$file | awk '{print $1}'`" = "$md5sum1" ] || \
+        [ "`md5sum /$file | awk '{print $1}'`" = "$md5sum2" ] || \
+        { echo "Verification failed on /$file" ; error=1 ; }
 done
 
 if [ "${error}" = "1" ] ; then
-    echo "Device OpenSSL is not in factory condition, refusing to install replacement"
-    exit 1
+    if [ "${FORCE_INSTALL}" != "1" ] ; then
+        echo "Device OpenSSL is not in factory condition, refusing to install replacement"
+        exit 1
+    else
+        echo "Device OpenSSL is not in factory condition, installing replacement anyway..."
+    fi
 fi
 
 # Make a backup of all OpenSSL files
